### ISSUE TITLE
AttributeError: module 'coloredlogs' has no attribute 'CAN_USE_BOLD_FONT'

### ISSUE THREAD

**Issue by Hermain** [yeswehack/ywh2bugtracker#1]
I wrote the following Dockerfile to use ywh2bt.

```
FROM python:3.8.2
RUN pip install ywh2bt
ENTRYPOINT [ "ywh-bugtracker", "--no-interactive", "--filename" ]
```

When I try to run any ymh-bugtracker command (by overwriting entrypoint to bin/bash and manually running any command) I get:
```
ywh-bugtracker -c -f test.yml
Traceback (most recent call last):
  File "/usr/local/bin/ywh-bugtracker", line 5, in <module>
    from ywh2bt.ywh2bt import main
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/ywh2bt.py", line 18, in <module>
    from ywh2bt.trackers.bugtracker import BugTracker
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/trackers/__init__.py", line 1, in <module>
    from . import ywhjira
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/trackers/ywhjira.py", line 6, in <module>
    from ywh2bt.config import BugTrackerConfig
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/config/__init__.py", line 3, in <module>
    from .abstract import ConfigObject, BugTrackerConfig
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/config/abstract.py", line 2, in <module>
    from ywh2bt.logging import logger
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/logging/__init__.py", line 54, in <module>
    logger = _setup_logger()
  File "/usr/local/lib/python3.8/site-packages/ywh2bt/logging/__init__.py", line 29, in _setup_logger
    levelname=dict(color="magenta", bold=coloredlogs.CAN_USE_BOLD_FONT),
AttributeError: module 'coloredlogs' has no attribute 'CAN_USE_BOLD_FONT'
# exit
```

I tried the same with python version 3.7 (which I found in your pipfile) with the same issue. Can you help me fix this?

**Comment by tbundt** [comment]
The CAN_USE_BOLD_FONT variable was removed from [coloredlogs](https://github.com/xolox/python-coloredlogs) in version 14.0:
https://github.com/xolox/python-coloredlogs/compare/12.0...14.0#diff-d469ea9b2f28f9f52d32f0c2bfb667dbL230

**Comment by Hermain** [comment]
Thank you that helps. But this should be fixed or at the very least be mentioned in the readme so that others don't have the same problem

**Comment by tchambaretaud** [comment]
Thank you for your issue.
Specific versions are fixed in the [last commit](https://github.com/yeswehack/ywh2bugtracker/commit/ce66e1c84588cd88c9facbeac450da264b072c78) and we publish a new release 0.5.1 in [pip](https://pypi.org/project/ywh2bt/#history).
