### ISSUE TITLE
AttributeError: 'ProgramConfig' object has no attribute 'name'

### ISSUE THREAD

**Issue by tbundt** [yeswehack/ywh2bugtracker#2]
When calling `ywh-bugtracker` I get the following error (after entering the password for Jira):

    Traceback (most recent call last):
      File "/usr/bin/ywh-bugtracker", line 11, in <module>
        load_entry_point('ywh2bt==0.5', 'console_scripts', 'ywh-bugtracker')()
      File "/usr/lib/python3.6/site-packages/ywh2bt/ywh2bt.py", line 77, in main
        configure_mode=options.configure,
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/main.py", line 50, in __init__
        self._build(config)
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/main.py", line 220, in _build
        self.yeswehack = self._config_ywh(config["yeswehack"])
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/main.py", line 358, in _config_ywh
        **ywh_config
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/yeswehack.py", line 84, in __init__
        self.get_interactive_info()
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/yeswehack.py", line 227, in get_interactive_info
        + Style.RESET_ALL
      File "/usr/lib/python3.6/site-packages/ywh2bt/config/yeswehack.py", line 218, in <listcomp>
        + ", ".join([pgm.name for pgm in self.programs])
    AttributeError: 'ProgramConfig' object has no attribute 'name'

When I replace the code from line 218 in `ywh2bt/config/yeswehack.py`:

    + ", ".join([pgm.name for pgm in self.programs])

with e.g. this:

    + ", ".join([str(pgm) for pgm in self.programs])

the error does not occur anymore. I would have created a pull request, but you'll probably find a nicer solution than I did.

**Comment by tchambaretaud** [comment]
Hello tbundt,

This issue has been fix after [last commit](https://github.com/yeswehack/ywh2bugtracker/commit/9692b0131c1df38dc2cd46afd9c1e686b6938657#diff-43a8c032da36f4d1a03416ee4c616917R218).

Thank you for your issue.
