### ISSUE TITLE
API does not return report title (None) and break cli mode

### ISSUE THREAD

**Issue by ralavay** [yeswehack/ywh2bugtracker#6]
YesWeHack API doesn't return report title and break the cli mode

```
$ ywh2bt sync -c config.json
...
Fetching reports for program "stashaway-bug-bounty-program": 13 report(s)
Traceback (most recent call last):
  File "/usr/local/bin/ywh2bt", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/cli/main.py", line 41, in run
    parsed.func(parsed)
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/cli/commands/synchronize.py", line 41, in synchronize
    synchronizer.synchronize()
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 124, in synchronize
    self._send_programs_from_yeswehack_configuration(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 177, in _send_programs_from_yeswehack_configuration
    self._send_reports_to_trackers(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 232, in _send_reports_to_trackers
    self._send_report_to_trackers(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 253, in _send_report_to_trackers
    self._send_report_to_tracker(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 279, in _send_report_to_tracker
    self._send_event(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/core/synchronizer/synchronizer.py", line 139, in _send_event
    self._listener.on_event(
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/cli/listener.py", line 67, in on_event
    self._on_event(event)
  File "/usr/local/lib/python3.9/site-packages/singledispatchmethod.py", line 69, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ywh2bt/cli/listener.py", line 131, in _on_start_send_report
    title = report.title[:title_max_len] + (report.title[title_max_len:] and '...')
TypeError: 'NoneType' object is not subscriptable
```

Debug a bit more then we found that in the event detail `title=None`

```
Report(raw_report=<yeswehack.api.Report object at 0x7f4ae00cb100>, report_id='xxx', title=None, local_id='xxx'
```

**Comment by m-honel-ywh2bt** [comment]
Thanks for your report and the patch you provided.

A new version [`2.5.4`](https://pypi.org/project/ywh2bt/) (820ccd51a6ebeedbd720faec6242331692c95937) inspired by your suggestion has been publish.
